### ISSUE TITLE
MXNet does not support NumPy 1.24

### ISSUE THREAD

**Issue by rkazants** [apache/mxnet#21165]
## Description
MXNet does not support NumPy 1.24

### Error Message
Conversion of MXNet models by using OpenVINO Model Optimizer will raise this issue

python3.8/site-packages/mxnet/numpy/utils.py:37: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  bool = onp.bool
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  module 'numpy' has no attribute 'bool'
[ ERROR ]  Traceback (most recent call last):
  File "openvino/tools/mo/openvino/tools/mo/main.py", line 50, in main
    ngraph_function = convert_model(**argv)
  File "openvino/tools/mo/openvino/tools/mo/convert.py", line 47, in convert_model
    return _convert(**args)
  File "openvino/tools/mo/openvino/tools/mo/convert_impl.py", line 932, in _convert
    raise e.with_traceback(None)
AttributeError: module 'numpy' has no attribute 'bool'
[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

(Paste the complete error message. Please also include stack trace by setting environment variable `DMLC_LOG_STACK_TRACE_DEPTH=100` before running your script.)

## To Reproduce
install numpy 1.24
install mxnet 1.9.1

## What have you tried to solve it?
installation of numpy 1.23 should solve this problem

## Environment
install numpy 1.24
install mxnet 1.9.1

**Comment by Ishticode** [comment]
Any update on this from mxnet team @leezu  🙂

**Comment by sharan21** [comment]
Hey is there any update on this issue? `import mxnet` still seems to be failing due to the aforementioned numpy AttributeError

**Comment by lijinghaooo** [comment]
I try numpy=1.19 and it works, hope this error will be fixed in the future
